"""
app_logs.py
-----------
Collects application-level logs for the local agent.

This module reads logs generated by user applications
(e.g., web apps, services, custom programs).
"""

from utils.formatter import format_log

# Example application log file path
# You can change this based on your application
APP_LOG_FILE = "sample_app.log"


def collect_app_logs(system_id, max_lines=50):
    """
    Collect recent application logs.

    Args:
        system_id (str): Unique system identifier
        max_lines (int): Number of recent log lines to read

    Returns:
        list: List of structured log dictionaries
    """
    logs = []

    try:
        with open(APP_LOG_FILE, "r", errors="ignore") as file:
            lines = file.readlines()[-max_lines:]

            for line in lines:
                line = line.strip()
                if not line:
                    continue

                logs.append(
                    format_log(
                        system_id=system_id,
                        source="application",
                        message=line,
                        level="INFO"
                    )
                )

    except FileNotFoundError:
        # Application log file not found
        pass
    except PermissionError:
        # No permission to read file
        pass
    except Exception:
        # Prevent agent crash due to unexpected error
        pass

    return logs
