"""
report_generator.py (FINAL VERSION)
-----------------------------------
Secure Forensic Report Generator

Features:
- Generates PDF forensic report
- Enforces system ownership (security)
- Includes logs + alerts + timeline + summary
- Court / SOC / Audit ready format
"""

from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
import os
from sqlalchemy import desc

from backend.database.models import System, Log, Alert


# =========================================================
# MAIN REPORT FUNCTION WITH LOG TYPE FILTERING
# =========================================================
def generate_report(system_id, user_id, log_type=None):
    """
    Generate secure PDF forensic report for a system

    Args:
        system_id (str): Target system
        user_id (int): Logged-in user (security)
        log_type (str): Filter by log type (application, system, network, security)

    Returns:
        str: Path to generated PDF
    """

    # --------------------------------------------------
    # SECURITY CHECK (CRITICAL)
    # --------------------------------------------------
    system = System.query.filter_by(
        system_id=system_id,
        owner_id=user_id
    ).first()

    if not system:
        raise PermissionError("Unauthorized system access")

    # --------------------------------------------------
    # FETCH DATA WITH OPTIONAL LOG TYPE FILTER
    # --------------------------------------------------
    query = Log.query.filter_by(system_id=system_id)
    
    if log_type:
        query = query.filter_by(log_type=log_type)
    
    logs = (
        query.order_by(desc(Log.timestamp))  # type: ignore
        .limit(300)
        .all()
    )

    alerts = (
        Alert.query.filter_by(system_id=system_id)
        .order_by(desc(Alert.created_at))  # type: ignore
        .all()
    )

    # --------------------------------------------------
    # OUTPUT FILE
    # --------------------------------------------------
    os.makedirs("reports", exist_ok=True)
    log_type_suffix = f"_{log_type}" if log_type else ""
    filename = f"forensic_report_{system_id}{log_type_suffix}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join("reports", filename)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    y = height - 2 * cm

    def write(text):
        nonlocal y
        c.drawString(2 * cm, y, text)
        y -= 0.6 * cm
        if y < 2 * cm:
            c.showPage()
            y = height - 2 * cm

    # --------------------------------------------------
    # HEADER
    # --------------------------------------------------
    write("AI-BASED CYBER FORENSIC INVESTIGATION REPORT")
    write("=" * 90)
    write(f"System ID        : {system.system_id}")
    write(f"Hostname         : {system.hostname}")
    write(f"Last Seen        : {system.last_seen}")
    write(f"Report Generated : {datetime.utcnow()}")
    write(f"Generated By     : User ID {user_id}")
    if log_type:
        write(f"Log Type Filter  : {log_type.upper()}")
    write("")
    write("Evidence Integrity: This report was generated automatically from tamper-resistant logs.")
    write("")

    # --------------------------------------------------
    # EXECUTIVE SUMMARY
    # --------------------------------------------------
    write("EXECUTIVE SUMMARY")
    write("-" * 90)
    write(f"Total Logs Collected   : {len(logs)}")
    write(f"Total Alerts Generated : {len(alerts)}")
    write("")

    critical = [a for a in alerts if a.severity == "Critical"]
    high = [a for a in alerts if a.severity == "High"]

    write(f"Critical Incidents : {len(critical)}")
    write(f"High Risk Events   : {len(high)}")
    write("")

    # --------------------------------------------------
    # ALERT DETAILS
    # --------------------------------------------------
    write("DETECTED SECURITY INCIDENTS")
    write("-" * 90)

    if alerts:
        for alert in alerts:
            write(
                f"[{alert.severity}] {alert.created_at} | {alert.description}"
            )
    else:
        write("No security alerts detected.")

    write("")

    # --------------------------------------------------
    # FORENSIC TIMELINE
    # --------------------------------------------------
    write("FORENSIC TIMELINE (LAST 50 EVENTS)")
    write("-" * 90)

    for log in logs[:50]:
        write(
            f"{log.timestamp} | {log.log_type} | {log.source} | {log.level} | {log.message[:80]}"
        )

    write("")

    # --------------------------------------------------
    # RAW LOG EVIDENCE
    # --------------------------------------------------
    write("RAW LOG EVIDENCE (LAST 100 RECORDS)")
    write("-" * 90)

    for log in logs[:100]:
        write(
            f"{log.timestamp} | {log.log_type} | {log.source} | {log.level} | {log.message[:70]}"
        )

    write("")
    write("=" * 90)
    write("END OF FORENSIC REPORT")

    c.save()
    return file_path
